### ISSUE TITLE
No update due to multiple "latest" tag

### ISSUE THREAD

**Issue by cmercier141** [hrektts/docker-plantuml#2]
Hello.
Would it be possible to add a tag with the version at the last commit so that we can choose it when we get the docker image.
I had 'hrektts/plantuml:latest' from a previous tag and so there was no update with the new version.
Thanks to you.

**Comment by hrektts** [comment]
Done. Please check Docker Hub.

**Comment by cmercier141** [comment]
It's okay, thanks to you :)
